### PR TITLE
Fall back to 'en' when browser's language is unsupported. Fixes #184.

### LINKED ISSUE #184: FAQ doesn't work when browsers preffered language is not en/fr/sv
When visiting the web interface with a browser set to prefer a language not supported by *zonemaster-gui*, the FAQ page just stays empty:

kookaburra_20170630_161027

Tested on *zonemaster.net* & *zonemaster.se* with:
- Firefox 54, `Accept-Language: cs,en-US;q=0.7,en;q=0.3`
- Chrome 61, `Accept-Language: cs,en-US;q=0.8,en;q=0.6`

I guess the best (and probably easiest) solution would be just to fall back to English here, like the other translations (menu, form labels) do…

### PR DESCRIPTION
**Pull request by helb**
See issue #184.

Hardcoding the language codes in JS is certainly not ideal, but i have not found any config file of other good place to get them from (apart from `Frontend.pm` and `index.tt`, where they are hardcoded, too).

Another way would be to make use of the language switcher (ES6 used for brevity):

```javascript
let supportedLangs = [];
document.querySelectorAll("lang").forEach((lang) => supportedLangs.push(lang.lang));
console.log(supportedLangs);  // -> ["en", "fr", "sv"]
supportedLangs.includes("en") // -> true
supportedLangs.includes("cs") // -> false

// so we can do something like:
lang = supportedLangs.includes(browserLang) ? browserLang : "en";
```
…but i'm not too in favor of querying the DOM just for this.

### CODE REVIEW

**Comment by helb** [comment]
Travis build seems to be broken for some reason:

```
! Installing Zonemaster failed. See /home/travis/.cpanm/work/1498835541.6054/build.log for details. Retry with --force to force install it.
```

No idea what to do with this, i'm not familiar with Perl…

**Comment by matsduf** [comment]
The Travis servers sometimes missed binary msgfmt, and then Zonemaster Engine fails to be installed. We have a solution for that, but is has not yet being released to CPAN, man before that we will sometimes get the error from Travis.

https://github.com/dotse/zonemaster-engine/pull/305

File: zm_app/public/javascripts/dnscheck.js [hunk 1]
```diff
@@ -27,12 +27,14 @@ dnscheck.factory('customLoader', function ($http, $q, $timeout) {
...
 	var lang;
-		if (navigator.userLanguage) // Explorer
+		if (navigator.userLanguage) { // Explorer
 			lang = navigator.userLanguage.substring(0, 2);
-		else if (navigator.language) // FF
-			lang = navigator.languages ? navigator.languages[0].substring(0, 2) : (navigator.language.substring(0, 2) || navigator.userLanguage.substring(0, 2));
-		else
+		} else if (navigator.language) { // FF
+			var browserLang = navigator.languages ? navigator.languages[0].substring(0, 2) : (navigator.language.substring(0, 2) || navigator.userLanguage.substring(0, 2));
+			lang = browserLang.match(/(en|fr|sv)/i) ? browserLang : "en";
```
Comment (matsduf) [inline zm_app/public/javascripts/dnscheck.js]: Should it be hard coded here what languages that are supported? I think that should be in as few places as possible.

**Comment by pamasse** [comment]
it's ok for me

**Comment by sandoche2k** [comment]
as both reviewers @matsduf and @pamasse has approved the PR, i am closing it.

**Comment by matsduf** [comment]
Travis fails because of the issue reported in #203. @pamasse, please look at my review comment.

File: zm_app/public/javascripts/dnscheck.js [hunk 2]
```diff
@@ -27,12 +27,14 @@ dnscheck.factory('customLoader', function ($http, $q, $timeout) {
...
 	var lang;
-		if (navigator.userLanguage) // Explorer
+		if (navigator.userLanguage) { // Explorer
 			lang = navigator.userLanguage.substring(0, 2);
-		else if (navigator.language) // FF
-			lang = navigator.languages ? navigator.languages[0].substring(0, 2) : (navigator.language.substring(0, 2) || navigator.userLanguage.substring(0, 2));
-		else
+		} else if (navigator.language) { // FF
+			var browserLang = navigator.languages ? navigator.languages[0].substring(0, 2) : (navigator.language.substring(0, 2) || navigator.userLanguage.substring(0, 2));
+			lang = browserLang.match(/(en|fr|sv|da)/i) ? browserLang : "en";
```
Comment (matsduf) [inline zm_app/public/javascripts/dnscheck.js]: @pamasse, is it OK to hard code supported languages here?

Comment (pamasse) [reply zm_app/public/javascripts/dnscheck.js]: For this version, yes. Other solutions are more complex and can be done in the new gui.
